apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-shop
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devops-shop
  template:
    metadata:
      labels:
        app: devops-shop
    spec:
      containers:
        - name: devops-shop
          image: <REPLACED_BY_CICD>
          ports:
            - containerPort: 5000
